acoustid/web/views/apps.py
import logging
import json
from flask import Blueprint, render_template, request, redirect, url_for, abort, current_app, session
from acoustid.web import db
from acoustid.web.utils import require_user, is_valid_email, is_valid_url
from acoustid.data.application import find_applications_by_account, insert_application, update_application
from acoustid.data.stats import find_application_lookup_stats
from .stats import prepare_chart_data

logger = logging.getLogger(__name__)

apps_page = Blueprint('apps', __name__)


@apps_page.route('/my-applications')
def applications():
    user = require_user()
    title = 'Your Applications'
    applications = find_applications_by_account(db.session.connection(), user.id)
    return render_template('applications.html', title=title,
        applications=applications)


@apps_page.route('/application/<application_id>')
def application(application_id):
    user = require_user()
    title = 'Your Application'
    conn = db.session.connection()
    application = conn.execute("""
        SELECT * FROM application
        WHERE id = %s
    """, (application_id,)).fetchone()
    if application is None:
        abort(404)
    if user.id != application['account_id'] and not user.is_admin:
        abort(404)
    monthly_stats = conn.execute("""
        SELECT
            date_trunc('month', date) AS month,
            sum(count_hits) + sum(count_nohits) AS lookups
        FROM stats_lookups
        WHERE application_id = %s
        GROUP BY date_trunc('month', date)
        ORDER BY date_trunc('month', date) DESC
    """, (application_id,)).fetchall()
    lookups = find_application_lookup_stats(conn, application_id)
    return render_template('application.html', title=title,
        app=application, monthly_stats=monthly_stats,
        lookups=lookups,
        lookups_json=json.dumps(prepare_chart_data(lookups)))


@apps_page.route('/new-application', methods=['GET', 'POST'])
def new_application():
    user = require_user()
    errors = []
    title = 'New Application'
    if request.form.get('submit'):
        name = request.form.get('name')
        if not name:
            errors.append('Missing application name')
        version = request.form.get('version')
        if not version:
            errors.append('Missing version number')
        email = request.form.get('email')
        if email and not is_valid_email(email):
            errors.append('Invalid email address')
        website = request.form.get('website')
        if website and not is_valid_url(website):
            errors.append('Invalid website URL')
        if not errors:
            insert_application(db.session.connection(), {
                'name': name,
                'version': version,
                'email': email,
                'website': website,
                'account_id': user.id,
            })
            db.session.commit()
            return redirect(url_for('.applications'))
    return render_template('new-application.html', title=title,
        form=request.form, errors=errors)



@apps_page.route('/application/<application_id>/edit', methods=['GET', 'POST'])
def edit_application(application_id):
    user = require_user()
    conn = db.session.connection()
    application = conn.execute("""
        SELECT * FROM application
        WHERE id = %s
    """, (application_id,)).fetchone()
    if application is None:
        abort(404)
    if user.id != application['account_id']:
        abort(404)
    errors = []
    title = 'Edit Application'
    if request.form.get('submit'):
        form = request.form
        name = request.form.get('name')
        if not name:
            errors.append('Missing application name')
        version = request.form.get('version')
        if not version:
            errors.append('Missing version number')
        email = request.form.get('email')
        if email and not is_valid_email(email):
            errors.append('Invalid email address')
        website = request.form.get('website')
        if website and not is_valid_url(website):
            errors.append('Invalid website URL')
        if not errors:
            update_application(conn, application.id, {
                'name': name,
                'version': version,
                'email': email,
                'website': website,
                'account_id': user.id,
            })
            db.session.commit()
            return redirect(url_for('.application', application_id=application.id))
    else:
        form = {}
        form['name'] = application['name']
        form['version'] = application['version'] or ''
        form['email'] = application['email'] or ''
        form['website'] = application['website'] or ''
    return render_template('edit-application.html', title=title,
        form=form, errors=errors, app=application)

acoustid/web/views/stats.py
# Copyright (C) 2011, 2015 Lukas Lalinsky
# Distributed under the MIT license, see the LICENSE file for details.

import logging
import json
from flask import Blueprint, render_template, request, redirect, url_for, abort, current_app
from acoustid.web import db
from acoustid.data.stats import (
    find_current_stats,
    find_daily_stats,
    find_lookup_stats,
    find_application_lookup_stats,
)

logger = logging.getLogger(__name__)

stats_page = Blueprint('stats', __name__)


def percent(x, total):
    if total == 0:
        x = 0
        total = 1
    return '%.2f' % (100.0 * x / total,)


def prepare_pie_chart_data(stats, pattern):
    track_mbid_data = []
    track_mbid_sum = 0
    for i in range(11):
        value = stats.get(pattern % i, 0)
        if i != 0:
            track_mbid_sum += value
        track_mbid_data.append(value)
    track_mbid = []
    for i, count in enumerate(track_mbid_data):
        if i == 0:
            continue
        track_mbid.append({
            'i': i,
            'count': count,
            'percent': percent(count, track_mbid_sum),
        })
    return track_mbid


def prepare_chart_data(stats):
    for item in stats:
        item['date'] = item['date'].strftime('%Y-%m-%d')
    return stats


@stats_page.route('/stats')
def stats():
    title = 'Statistics'
    stats = find_current_stats(db.session.connection())
    basic = {
        'submissions': stats.get('submission.all', 0),
        'fingerprints': stats.get('fingerprint.all', 0),
        'tracks': stats.get('track.all', 0),
        'mbids': stats.get('mbid.all', 0),
        'contributors': stats.get('account.active', 0),
    }
    track_mbid = prepare_pie_chart_data(stats, 'track.%dmbids')
    mbid_track = prepare_pie_chart_data(stats, 'mbid.%dtracks')
    basic['tracks_with_mbid'] = basic['tracks'] - stats.get('track.0mbids', 0)
    basic['tracks_with_mbid_percent'] = percent(basic['tracks_with_mbid'], basic['tracks'])
    additions = find_daily_stats(db.session.connection(), ['track.all', 'mbid.all'])
    lookups = find_lookup_stats(db.session.connection())
    return render_template('stats.html', title=title, basic=basic,
        track_mbid=track_mbid, mbid_track=mbid_track,
        additions_json=json.dumps(prepare_chart_data(additions)),
        lookups_json=json.dumps(prepare_chart_data(lookups)))

acoustid/web/views/user.py
import json
import base64
import urllib2
import logging
import random
from itsdangerous import URLSafeSerializer
from rauth import OAuth2Service
from openid import oidutil, fetchers
from openid.consumer import consumer as openid
from openid.extensions import ax, sreg
from flask import Blueprint, render_template, request, redirect, url_for, abort, current_app, session
from acoustid.web import db
from acoustid.web.utils import require_user, is_our_url
from acoustid.models import Account, AccountOpenID, AccountGoogle
from acoustid.utils import generate_api_key
from acoustid.data.account import (
    lookup_account_id_by_mbuser,
    lookup_account_id_by_openid,
    insert_account,
    get_account_details,
    reset_account_apikey,
    update_account_lastlogin,
    is_moderator,
)

logger = logging.getLogger(__name__)

user_page = Blueprint('user', __name__)


# monkey-patch uidutil.log to use the standard logging framework
openid_logger = logging.getLogger('openid')
def log_openid_messages(message, level=0):
    openid_logger.info(message)
oidutil.log = log_openid_messages


# force the use urllib2 with a timeout
fetcher = fetchers.Urllib2Fetcher()
fetcher.urlopen = lambda req: urllib2.urlopen(req, timeout=5)
fetchers.setDefaultFetcher(fetcher)


@user_page.route('/login', methods=['GET', 'POST'])
def login():
    if 'id' in session:
        return redirect(url_for('general.index'))
    errors = list(request.args.getlist('error'))
    if request.method == 'POST':
        login_method = request.form.get('login')
        if login_method == 'musicbrainz':
            return musicbrainz_login()
        elif login_method == 'google':
            return google_login()
        elif login_method == 'openid':
            return openid_login()
    return render_template('login.html', errors=errors,
        return_url=request.values.get('return_url'))


def find_or_create_musicbrainz_user(mb_user_name):
    user = db.session.query(Account).filter_by(mbuser=mb_user_name).first()
    if user is not None:
        return user

    user = Account()
    user.name = mb_user_name
    user.mbuser = mb_user_name
    user.apikey = generate_api_key()
    user.submission_count = 0
    db.session.add(user)
    db.session.flush()

    return user


def login_user_and_redirect(user_id, return_url=None):
    session['id'] = user_id
    if not return_url:
        return_url = request.values.get('return_url')
    if return_url and is_our_url(return_url):
        return redirect(return_url)
    return redirect(url_for('general.index'))


def handle_musicbrainz_oauth2_login():
    musicbrainz = OAuth2Service(
        name='musicbrainz',
        client_id=current_app.config['MB_OAUTH_CLIENT_ID'],
        client_secret=current_app.config['MB_OAUTH_CLIENT_SECRET'],
        base_url='https://musicbrainz.org',
        authorize_url='https://musicbrainz.org/oauth2/authorize',
        access_token_url='https://musicbrainz.org/oauth2/token',
    )

    serializer = URLSafeSerializer(current_app.config['SECRET_KEY'])

    code = request.args.get('code')
    if not code:
        token = str(random.getrandbits(64))
        session['mb_login_token'] = token
        url = musicbrainz.get_authorize_url(**{
            'response_type': 'code',
            'scope': 'profile',
            'redirect_uri': url_for('.musicbrainz_login', _external=True),
            'state': serializer.dumps({
                'return_url': request.values.get('return_url'),
                'token': token,
            }),
        })
        return redirect(url)

    serialized_state = request.args.get('state')
    if serialized_state:
        state = serializer.loads(serialized_state)
    else:
        state = {}

    token = session.get('mb_login_token')
    if not token:
        raise Exception('token not found in session')

    if token != state.get('token'):
        raise Exception('token from session does not match token from oauth2 state')

    auth_session = musicbrainz.get_auth_session(data={
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': url_for('.musicbrainz_login', _external=True),
    }, decoder=json.loads)

    response = auth_session.get('oauth2/userinfo').json()

    user = find_or_create_musicbrainz_user(response['sub'])
    logger.info('MusicBrainz user %s "%s" logged in', user.id, user.name)

    return login_user_and_redirect(user.id, return_url=state.get('return_url'))


@user_page.route('/login/musicbrainz')
def musicbrainz_login():
    try:
        response = handle_musicbrainz_oauth2_login()
        db.session.commit()
    except Exception:
        logger.exception('MusicBrainz login failed')
        db.session.rollback()
        return redirect(url_for('.login', error='MusicBrainz login failed'))
    return response


def handle_openid_login_request():
    openid_url = request.form['openid_identifier']
    try:
        consumer = openid.Consumer(session, None)
        openid_req = consumer.begin(openid_url)
    except openid.DiscoveryFailure:
        logger.exception('Error in OpenID discovery')
        raise
    else:
        if openid_req is None:
            raise Exception('No OpenID services found for the given URL')
        else:
            ax_req = ax.FetchRequest()
            ax_req.add(ax.AttrInfo('http://schema.openid.net/contact/email',
                      alias='email'))
            ax_req.add(ax.AttrInfo('http://axschema.org/namePerson/friendly',
                      alias='nickname'))
            openid_req.addExtension(ax_req)
            url = openid_req.redirectURL(get_openid_realm(),
                url_for('.openid_login', return_url=request.values.get('return_url'), _external=True))
            return redirect(url)
    raise Exception('OpenID login failed')


def handle_openid_login_response():
    conn = db.session.connection()
    consumer = openid.Consumer(session, None)
    info = consumer.complete(request.args, request.url)
    if info.status == openid.SUCCESS:
        openid_url = info.identity_url
        values = {}
        ax_resp = ax.FetchResponse.fromSuccessResponse(info)
        if ax_resp:
            attrs = {
                'email': 'http://schema.openid.net/contact/email',
                'name': 'http://schema.openid.net/namePerson/friendly',
            }
            for name, uri in attrs.iteritems():
                try:
                    value = ax_resp.getSingle(uri)
                    if value:
                        values[name] = value
                except KeyError:
                    pass
        account_id = lookup_account_id_by_openid(conn, openid_url)
        if not account_id:
            account_id, account_api_key = insert_account(conn, {
                'name': 'OpenID User',
                'openid': openid_url,
            })
        logger.info("Successfuly identified OpenID user %s (%d) with email '%s' and nickname '%s'",
            openid_url, account_id, values.get('email', ''), values.get('name', ''))
        return login_user_and_redirect(account_id)
    elif info.status == openid.CANCEL:
        raise Exception('OpenID login has been canceled')
    else:
        raise Exception('OpenID login failed')


def handle_openid_login():
    if 'openid.mode' in request.args:
        return handle_openid_login_response()
    else:
        return handle_openid_login_request()


@user_page.route('/login/openid')
def openid_login():
    try:
        response = handle_openid_login()
        db.session.commit()
    except Exception:
        logger.exception('OpenID login failed')
        db.session.rollback()
        return redirect(url_for('.login', error='OpenID login failed'))
    return response


def get_openid_realm():
    return url_for('general.index', _external=True).rstrip('/')


def find_or_create_google_user(google_user_id, openid=None):
    user = db.session.query(Account).join(AccountGoogle).\
        filter(AccountGoogle.google_user_id == google_user_id).first()
    if user is not None:
        return user

    if openid is not None:
        user = db.session.query(Account).join(AccountOpenID).\
            filter(AccountOpenID.openid == openid).first()
        if user is not None:
            db.session.query(AccountOpenID).\
                filter(AccountOpenID.openid == openid).delete()
            logger.info("Migrated OpenID user %s to Google user %s", openid, google_user_id)

    if user is None:
        user = Account()
        user.name = 'Google Account'
        user.apikey = generate_api_key()
        user.submission_count = 0
        db.session.add(user)
        db.session.flush()
        logger.info("Created user %s (%s)", user.id, user.name)

    google_user = AccountGoogle()
    google_user.account = user
    google_user.google_user_id = google_user_id
    db.session.add(google_user)
    logger.info("Associated user %s (%s) with Google user %s", user.id, user.name, google_user_id)

    return user


def handle_google_oauth2_login():
    google = OAuth2Service(
        name='google',
        client_id=current_app.config['GOOGLE_OAUTH_CLIENT_ID'],
        client_secret=current_app.config['GOOGLE_OAUTH_CLIENT_SECRET'],
        base_url='https://google.com',
        authorize_url='https://accounts.google.com/o/oauth2/auth',
        access_token_url='https://www.googleapis.com/oauth2/v3/token',
    )

    code = request.args.get('code')
    if not code:
        url = google.get_authorize_url(**{
            'response_type': 'code',
            'access_type': 'online',
            'scope': 'openid',
            'redirect_uri': url_for('.google_login', _external=True),
            'openid.realm': get_openid_realm(),
        })
        return redirect(url)

    response = json.loads(google.get_raw_access_token(data={
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': url_for('.google_login', _external=True),
    }).content)

    header, payload, secret = str(response['id_token']).split('.')

acoustid/web/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head> 
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% if title %}{{ title }} | {% endif %}AcoustID</title> 
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300">
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:400,600">
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/{{ bootstrap_version }}/css/bootstrap.min.css">
  {% block extra_css %}{% endblock %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='acoustid.css') }}" />
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
	<!--<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18981078-1']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
 
	</script> -->
</head> 
<body>

{% if show_maintenace_banner %}
  <div class="maintenance-header">
    <div class="container">
      <p>
        AcoustID is currently in read-only mode for maintenance.
      </p>
    </div>
  </div>
{% endif %}

{% if show_donate_banner %}
  <div class="donate-header">
    <div class="container">
      <div class="row">
        <div class="col-md-10">
          <p>
            Dear users &mdash;
            AcoustID provides free service to a number of open source applications.
            If you are using such an application and find AcoustID useful, please consider donating a
            small amount, to keep it running smoothly and stay free.
            <i>Thank you.</i>
          </p>
        </div>
        <div class="col-md-2">
          <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="RRBS25ADWPK2E">
            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endif %}

  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand">
          <a href="{{ url_for('general.index') }}" title="AcoustID">
            <img src="{{ url_for('static', filename='acoustid.svg') }}" alt="AcoustID">
          </a>
          <small>open source audio identification</small>
        </div>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{{ url_for('general.applications') }}">Applications</a></li>
          <li><a href="{{ url_for('stats.stats') }}">Statistics</a></li>
          <li><a href="{{ url_for('general.docs') }}">Documentation</a></li>
          <li><a href="{{ url_for('general.donate') }}">Donate</a></li>
          {% if account_id %}
          <li><a href="{{ url_for('user.logout') }}">Sign out</a></li>
          {% else %}
          <li><a href="{{ url_for('user.login') }}">Sign in</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

	<div class="container"> 

    <div class="content">
      {% block content %}{% endblock %}
    </div>

	</div> 

	<div class="footer">
    <div class="container">
      <p class="text-muted">Software created by <a href="https://oxygene.sk/">Lukáš Lalinský</a>, hosted by <a href="https://acoustid.biz">AcoustID OÜ</a>, data crowd-sourced by <a href="{{ url_for('stats.stats') }}">thousands of contributors</a>.</p>
      <p class="text-muted">
        <a href="{{ url_for('general.contact') }}">Contact</a> |
        <a href="https://oxygene.sk/category/acoustid/">Blog</a> |
        <a href="https://twitter.com/acoustid">Twitter</a> |
        <a href="https://www.facebook.com/acoustid">Facebook</a>
      </p>
    </div>
	</div>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/{{ jquery_version }}/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/{{ bootstrap_version }}/js/bootstrap.min.js"></script>
  {% block extra_js %}{% endblock %}

</body> 
</html> 
 

acoustid/web/templates/admin_index.html
{% extends "_base.html" %}
{% block content %}

<h2>Administration</h2>

<ul>
  <li>
    Statistics
    <ul>
      <li><a href="{{ url_for("admin.stats_apps") }}">Applications</a></li>
    </ul>
  </li>
</ul>

{% endblock %}

acoustid/web/templates/admin_stats_apps.html
{% extends "_base.html" %}
{% block content %}

<h2>Application statistics</h2>

<p>
Show for
{% set comma = joiner(", ") %}
{% for m in last_months -%}
    {{- comma() -}}
    {%- if m == month -%}
    <b>{{ m.strftime("%B, %Y") }}</b>
    {%- else -%}
    <a href="{{ url_for("admin.stats_apps", month=m.strftime("%Y-%m")) }}">{{ m.strftime("%B, %Y") }}</a>
    {%- endif -%}
{%- endfor %}
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Application</th>
      <th>Version</th>
      <th class="text-right" style="width:8em">Hits</th>
      <th class="text-right" style="width:8em">Misses</th>
      <th class="text-right" style="width:8em">Requests</th>
    </tr>
  </thead>
  <tbody>
  {% for app, counts in stats %}
    <tr>
      <td><a href="{{ url_for("apps.application", application_id=app.id) }}">{{ app.name }}</a></td>
      <td>{{ app.version }}</td>
      <td class="text-right text-good">{{ (100 * counts.hits / counts.all) | round(1) }}%</td>
      <td class="text-right text-bad">{{ (100 - 100 * counts.hits / counts.all) | round(1) }}%</td>
      <td class="text-right">
      {% if counts.all > 1000000 %}
        <span title="{{ counts.all }}">{{ (counts.all / 1000000) | round(1) }}M</span>
      {% elif counts.all > 1000 %}
        <span title="{{ counts.all }}">{{ (counts.all / 1000) | round(1) }}K</span>
      {% else %}
        {{ counts.all }}
      {% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

acoustid/web/templates/application.html
{% extends "_base.html" %}
{% block content %}

<h2>Application "{{ app.name }}"</h2>

<h3>Details</h3>

<ul>
  <li><b>API key:</b> <code>{{ app.apikey }}</code></li>
  <li><b>Version:</b> {{ app.version }}</li>
  <li><b>Email:</b> {% if app.email %}<a href="mailto:{{ app.email }}">{{ app.email }}</a>{% else %}none{% endif %}</li>
  <li><b>Website:</b> {% if app.website %}<a href="{{ app.website }}">{{ app.website }}</a>{% else %}none{% endif %}</li>
</ul>

{% if app.account_id == session.id %}
<p>
  <a class="btn btn-default" href="{{ url_for('.edit_application', application_id=app.id) }}">Edit details</a>
</p>
{% endif %}

{% if lookups %}
<h3>Searches during the last 30 days</h3>
<div id="chart-searches" class="chart"></div>
{% endif %}

{% if monthly_stats %}
<h3>Searches per month</h3>
<table class="table">
  {% for m in monthly_stats %}
  <tr>
    <td>{{ m.month.strftime('%B %Y') }}</td>
    <td class="text-right">{{ m.lookups }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

{% endblock %}

{% block extra_css %}
{% if lookups %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/{{ morris_js_version }}/morris.css">
{% endif %}
{% endblock %}

{% block extra_js %}
{% if lookups %}
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/{{ raphael_js_version }}/raphael-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/{{ morris_js_version }}/morris.min.js"></script>
<script>
$(document).ready(function() {

  new Morris.Line({
    element: 'chart-searches',
    data: {{ lookups_json|safe }},
    xkey: 'date',
    ykeys: ['count', 'count_hits', 'count_nohits'],
    xLabels: 'day',
    xLabelFormat: function (x) { return x.toDateString(); },
    labels: ['All', 'Hits', 'Misses'],
    lineColors: ['#4572A7', '#AA4643', '#89A54E', '#80699B', '#3D96AE', '#DB843D', '#92A8CD', '#A47D7C', '#B5CA92'],
    hideHover: 'auto',
    resize: true
  });

});
</script>
{% endif %}
{% endblock %}

acoustid/web/templates/applications.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

{% if applications %}

<p>
	If you are the developer of an application that uses the AcoustID web service, please register your application.
	So far you've registered the following applications:
</p>

<table class="table">
<thead>
	<tr>
		<th>Name</th>
		<th>Version</th>
		<th>API Key</th>
	</tr>
</thead>
<tbody>
{% for app in applications %}
	<tr>
		<td><a href="{{ url_for('.application', application_id=app.id) }}">{{ app.name }}</a></td>
		<td>{{ app.version }}</td>
		<td><code>{{ app.apikey }}</code></td>
	</tr>
{% endfor  %}
</tbody>
</table>

{% else %}

<p>
	You do not have any registered applications. If you are the developer of an application that uses the AcoustID web service, please register your application.
</p>

{% endif %}

<p>
  <a class="btn btn-default" href="{{ url_for('.new_application') }}">Register a new application</a>
</p>

{% endblock %}

acoustid/web/templates/compare_fingerprints.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

<p>
  <button class="btn btn-default" id="move-up">Move Up</button>
  <button class="btn btn-default" id="move-down">Move Down</button>
  Offset: <span id="offset">0</span>
</p>

<p><canvas style="border: solid 2px #C5C5C5;" id="fp-img" width="32" height="0"></canvas></p>

<p>
  Back to <a href="{{ url_for('.fingerprint', fingerprint_id=fingerprint_1.id) }}">fingerprint #{{ fingerprint_1.id }}</a>
  or <a href="{{ url_for('.fingerprint', fingerprint_id=fingerprint_2.id) }}">fingerprint #{{ fingerprint_2.id }}</a>
</p>

{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{{ url_for('static', filename='fputils.js') }}"></script>
<script type="text/javascript">
$(document).ready(function () {
   var fp1 = {{ fingerprint_1.fingerprint }};
   var fp2 = {{ fingerprint_2.fingerprint }};
   var canvas = document.getElementById('fp-img');
   var offset = 0;

   function repaint() {
       paintFingerprintDiff(canvas, fp1, fp2, offset);
       $("#offset").text(offset);
   }

   repaint();

   $('#move-up').click(function () {
       offset -= 1;
       repaint();
   });

   $('#move-down').click(function () {
       offset += 1;
       repaint();
   });

});
</script>
{% endblock %}

acoustid/web/templates/toggle_track_mbid_login.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

<p>We are sorry, but editing is only possible if you log in with a MusicBrainz account.</p>

{% endblock %}

acoustid/web/templates/track-not-found.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

<p>
    There is no track with ID {{ track_id }} in the AcoustID database.
</p>

{% endblock %}